TRI-51/Implement ticket edition
sirius-valley/tricker-backend pull request #81
Opened 2024-03-29 13:14 UTC by Juan-Bianchi

# Pull Request

## Description
This method should receive the ticket info and edit the ticket in the DB to match the data received.

## Ticket Link
[TRI-51](https://linear.app/tricker-sirius/issue/TRI-51/implement-ticket-edition)

## Steps to Reproduce
1. Check /src/domains/issue/issue.service.impl.ts and see updateIssueById method and updateIssueByProviderId method
2. I've created two different methods. One for updates from webhooks and the other using the issue local id.
3. If you want to test the method with and endpoint you can use /:issueId/flag/add or /:issueId/flag/remove enpoints. I've replaced  the former method to update blocking status with the new ones.

2024-04-01 22:41 UTC, luccar31 requested changes

2024-04-01 22:41 UTC, luccar31 commented on src/domains/issue/service/issue.service.impl.ts
> +    if (data.issueId === undefined) {
This kind of checks shouldn't be done because this is done already by Typescript. Split the `IssueUpdateInput` class in two, one for webhooks, with `providerId` not null and the other with our internal `id`. As you already have 2 methods, this change suits each one of them.

2024-04-01 22:41 UTC, luccar31 commented on src/domains/issue/dto/index.ts
> +export interface IssueUpdateInput {
Split this in 2 interfaces, one with `providerId` not null and the other with the `issueId` not null

2024-04-01 23:06 UTC, Juan-Bianchi commented on src/domains/issue/dto/index.ts
> +export interface IssueUpdateInput {
solved

2024-04-02 00:36 UTC, Juan-Bianchi commented on src/domains/issue/service/issue.service.impl.ts
> +    if (data.issueId === undefined) {
done

2024-04-02 01:03 UTC, luccar31 approved these changes

2024-04-02 01:04 UTC, merged